# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock


###########################################

# Site settings
title:
   navbar: Ryan L McIntyre - App Developer
   header: Ryan L McIntyre - Application Developer
   head: Ryan L McIntyre (ryanoasis) - Application Developer
email: ryanlmcintyre@gmail.com
url: https://ryanlmcintyre.com
description: "Application Developer with Full Stack Experience. Creator of Nerd Fonts and VimDevIcons"
skills:
  heading: "Application Developer - OSS Contributor - Vimmer"
  technical:
     - title: "JavaScript"
       years: 5
       rating: 7
       devicon: "javascript_badge"
     - title: "AngularJS"
       years: 1
       rating: 5
       devicon: "angular"
     - title: "jQuery"
       years: 4
       rating: 6
       devicon: "jquery"
     - title: "CSS"
       years: 8
       rating: 8
       devicon: "css3"
     - title: "Git"
       years: 6
       rating: 7
       devicon: "git"
     - title: "HTML"
       years: 8
       rating: 8
       devicon: "code"
     - title: "Python"
       years: 3
       rating: 6
       devicon: "python"
     - title: "PHP"
       years: 3
       rating: 6
       devicon: "php"
     - title: "Vim"
       years: 3
       rating: 7
       devicon: "vim"
     - title: "Bash"
       years: 5
       rating: 5
       devicon: "terminal"
     - title: "MySQL"
       years: 4
       rating: 5
       devicon: "mysql"
     - title: "Symfony"
       years: 4
       rating: 5
       devicon: "symfony_badge"
     - title: "GitHub"
       years: 5
       rating: 8
       devicon: "github"
     - title: "Jira"
       years: 6
       rating: 8
       devicon: "jira"
     - title: "Subversion"
       years: 3
       rating: 4
       devicon: ""
     - title: "Grunt"
       years: 3
       rating: 4
       devicon: "grunt"

meta_author: Ryan McIntyre

# Google webmaster tools
google_verify: 'UA-91025680-1'

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through enformed.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ryanlmcintyre
  - title: stack-overflow
    url: http://meta.stackoverflow.com/users/436159/ryanoasis
  - title: bitbucket
    url: https://bitbucket.org/ryanoasis

meta_author: Ryan McIntyre

# Google webmaster tools
google_verify: 'UA-91025680-1'

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through enformed.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ryanlmcintyre
  - title: stack-overflow
    url: http://meta.stackoverflow.com/users/436159/ryanoasis
  - title: bitbucket
    url: https://bitbucket.org/ryanoasis
  - title: github
    url: http://github.com/ryanoasis

# Postal address (add as many lines as necessary)
address:
  - line: Charlotte, NC 28202

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
