# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock


###########################################

# Site settings
title:
   navbar: Ryan L McIntyre - App Developer
   header: Ryan L McIntyre - Application Developer
   head: Ryan L McIntyre - Web Application Developer
url: https://ryanlmcintyre.com
description: "Full Stack Web Application Developer. Creator of Nerd Fonts and VimDevIcons"
skills:
  subheading: "Full Stack Web Application Developer. Creator of <a href='https://nerdfonts.com/' target='_blank'>Nerd Fonts</a> and <a href='https://github.com/ryanoasis/vim-devicons/' target='_blank'>VimDevIcons</a>"
  explanation: "The following ratings are my own personal and honest ratings of my experience and skill level on various subjects:"
  current_focus:
     - title: "JavaScript"
       devicon: "nf-dev-javascript_badge"
     - title: "Docker"
       devicon: "nf-linux-docker"
     - title: "React"
       devicon: "nf-dev-react"
     - title: "Webpack"
       devicon: "nf-mdi-webpack"
     - title: "Sass"
       devicon: "nf-dev-sass"
     - title: "Python"
       devicon: "nf-dev-python"
     - title: "Vim"
       devicon: "nf-dev-vim"
     - title: "Fonts"
       devicon: "nf-fa-font"
  technical:
     - title: "CSS"
       devicon: "nf-dev-css3"
     - title: "Git"
       devicon: "nf-dev-git"
     - title: "HTML"
       devicon: "nf-dev-code"
     - title: "Python"
       devicon: "nf-dev-python"
     - title: "JavaScript"
       devicon: "nf-dev-javascript_badge"
     - title: "AngularJS"
       devicon: "nf-dev-angular"
     - title: "jQuery"
       devicon: "nf-dev-jquery"
     - title: "PHP"
       devicon: "nf-dev-php"
     - title: "Java"
       devicon: "nf-dev-java"
     - title: "Vim"
       devicon: "nf-dev-vim"
     - title: "Bash"
       devicon: "nf-dev-terminal"
     - title: "MySQL"
       devicon: "nf-dev-mysql"
     - title: "Symfony"
       devicon: "nf-dev-symfony_badge"
     - title: "GitHub"
       devicon: "nf-dev-github"
     - title: "Jira"
       devicon: "nf-dev-jira"
     - title: "Subversion"
       devicon: "nf-oct-diff"
     - title: "Grunt"
       devicon: "nf-dev-grunt"
     - title: "Eclipse"
       devicon: "nf-dev-eclipse"
     - title: "Visual Studio"
       devicon: "nf-dev-visualstudio"
     - title: "Jekyll"
       devicon: "nf-dev-jekyll_small"

meta_author: Ryan McIntyre

# Google webmaster tools
google_verify: 'UA-91025680-1'

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through enformed.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

meta_author: Ryan McIntyre

# Google webmaster tools
google_verify: 'UA-91025680-1'

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through enformed.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

reCAPTCHA_site_key: 6LdfH5EUAAAAANTWUox7x93oB4PGWGCRJ226vhjb

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ryanlmcintyre/
  - title: stack-overflow
    url: http://meta.stackoverflow.com/users/436159/ryanoasis
  - title: github
    url: http://github.com/ryanoasis

social-contact:
  - title: linkedin
    url: https://www.linkedin.com/in/ryanlmcintyre/

# Postal address (add as many lines as necessary)
address:
  - line: Seattle, WA 98121

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
